# Generated by Django 5.2.8 on 2025-11-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investorprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='email',
        ),
    ]
