# Generated by Django 5.2.8 on 2025-11-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_remove_investorprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
